### ISSUE TITLE
Can not get the annotation data from the class and can not copy the annotation to the BeanDefinition

### ISSUE THREAD

**Issue by ZinChen2014** [decebals/pf4j-spring#1]
Hi, I found that it can not get the annotation when loading the classes from the plugins folder, so it can not inject the annotation  to the BeanDefinition. I debug the ExtensionsInjector class, and found that.
I want to use the spring mvc with this project. but it can not work. Is this a bug or am I using the wrong way?

**Comment by decebals** [comment]
Can you giveme more details about your use case? will be greate if you can add some code snippet.

**Comment by decebals** [comment]
@ZinChen2014 Can you confirm that this issue is fixed?
