### ISSUE TITLE
Any option to load new plugins on demand? 

### ISSUE THREAD

**Issue by loefflefarn** [decebals/pf4j-spring#5]
Hey,
is there any option to load new added plugins on demand, without the needing to deploy the app again?

Greetings!

**Comment by decebals** [comment]
It's a question related to PF4J.
See [PluginMnaager#loadPlugin](https://github.com/decebals/pf4j/blob/master/pf4j/src/main/java/org/pf4j/PluginManager.java#L74).

**Comment by loefflefarn** [comment]
Ah, nice! Thank you!
