### ISSUE TITLE
Could not make the demo app work

### ISSUE THREAD

**Issue by llatasa** [decebals/pf4j-spring#9]
Hi,

I have downloaded the demo app and imported it into Ecplipse. Then I executed the Boot class using the VM parameter -Dpf4j.mode=development.

The exception bellow appears when the application starts (the first line in the log):

Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'greetings': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.util.List org.pf4j.demo.Greetings.greetings; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.pf4j.demo.api.Greeting] found for dependency [collection of org.pf4j.demo.api.Greeting]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

Then I can see the two plugins being started:

WelcomePlugin.start()
WELCOMEPLUGIN
2018-03-18 23:44:40,778 DEBUG org.pf4j.AbstractPluginManager - Fire 'PluginStateEvent [plugin=welcome-plugin, newState=STARTED, oldState=CREATED]' to 'org.pf4j.DefaultExtensionFinder@731f8236'
2018-03-18 23:44:40,779 INFO org.pf4j.AbstractPluginManager - Start plugin 'hello-plugin@0.0.1'
2018-03-18 23:44:40,779 DEBUG org.pf4j.DefaultExtensionFactory - Create instance for plugin 'org.pf4j.demo.hello.HelloPlugin'
HelloPlugin.start()

And then I see log traces saying that no extensions were found, so the greeting messages are not being printed. 

Do you have an idea of what I could be forgetting? 

Once I get it working I'll test Service, Controller and RestController, I guess I will be able to use it with the information provided in other issues.

Thank you very much.

**Comment by decebals** [comment]
Did you follow the instructions from https://github.com/decebals/pf4j-spring#demo (inclusive the working directory)?

**Comment by llatasa** [comment]
Hi!

The working directory is set by default to ${workspace_loc:pf4j-spring-demo-app}, so I guess this value is correct. I have tried to set the value manually and I get the same result.

Thanks!

**Comment by decebals** [comment]
I cannot replicate yout error on demo. See below the proof:

![image](https://user-images.githubusercontent.com/1248311/37615307-a41ec6ba-2bb5-11e8-82aa-7a8acdcd8633.png)

**Comment by decebals** [comment]
Can you share (via GitHub) your demo?

**Comment by llatasa** [comment]
I will upload my demo as soon as possible. In the meanwhile, some information in case it helps:

- I'm using Java 8 instead of 7
- I am using pf4j-spring version 0.4.0. So I modified the pom file to use this instead of 0.5.0-SNAPSHOT.
- I'm now trying with version 0.5.0-SNAPSHOT, just in case, but the lib is not found in the repository. I have tried using this lines:

<repositories>
    <repository>
        <id>sonatype-nexus-snapshots</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>

But if I access this url from a web browser, I can't see 0.5.0-SNAPSHOP: https://oss.sonatype.org/content/repositories/snapshots/org/pf4j/pf4j-spring/

Please let me know if all this gives you an idea. In any case, I'll upload the project and tell you when it's available for download.

Thanks again!

**Comment by decebals** [comment]
Version 0.4.0 is the latest. Version 0.5.0-SNAPSHOT is not available because is the same with 04.0 for the moment (see https://github.com/decebals/pf4j-spring/commits/master).

**Comment by llatasa** [comment]
Hi,

you can download my demo project from this URL:

http://acacia.duranda.net/demo.zip

Basically, I have replaced 0.5.0-SNAPSHOT with 0.4.0 in all the pom.xml files. Then executed it in eclipse.

**Comment by decebals** [comment]
https://groups.google.com/forum/m/#!topic/pf4j/oQP4Cm2IJn8

**Comment by llatasa** [comment]
Hi,

you are right! The answer was in that group and in some links referred there. I had to enable Annotation Processing in Eclipse, but doing it at project level was not enough. I have read this:

https://immutables.github.io/apt.html

After installing and configuring the m2e-apt plugin the problem dissapeared.

Hope this helps anyone else.

Thank you so much :-).
